//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TxFlow.Debug.WFTracking.TxFlowDebugServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TxFlowDebugServiceReference.IWorkflowDebugService")]
    public interface IWorkflowDebugService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowDebugService/ActivityExecuted", ReplyAction="http://tempuri.org/IWorkflowDebugService/ActivityExecutedResponse")]
        void ActivityExecuted(string workflowDefinitionID, string workflowInstanceID, string activityID, System.Collections.Generic.Dictionary<string, object> variableValues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowDebugService/ActivityExecuted", ReplyAction="http://tempuri.org/IWorkflowDebugService/ActivityExecutedResponse")]
        System.Threading.Tasks.Task ActivityExecutedAsync(string workflowDefinitionID, string workflowInstanceID, string activityID, System.Collections.Generic.Dictionary<string, object> variableValues);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorkflowDebugServiceChannel : TxFlow.Debug.WFTracking.TxFlowDebugServiceReference.IWorkflowDebugService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkflowDebugServiceClient : System.ServiceModel.ClientBase<TxFlow.Debug.WFTracking.TxFlowDebugServiceReference.IWorkflowDebugService>, TxFlow.Debug.WFTracking.TxFlowDebugServiceReference.IWorkflowDebugService {
        
        public WorkflowDebugServiceClient() {
        }
        
        public WorkflowDebugServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkflowDebugServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkflowDebugServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkflowDebugServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ActivityExecuted(string workflowDefinitionID, string workflowInstanceID, string activityID, System.Collections.Generic.Dictionary<string, object> variableValues) {
            base.Channel.ActivityExecuted(workflowDefinitionID, workflowInstanceID, activityID, variableValues);
        }
        
        public System.Threading.Tasks.Task ActivityExecutedAsync(string workflowDefinitionID, string workflowInstanceID, string activityID, System.Collections.Generic.Dictionary<string, object> variableValues) {
            return base.Channel.ActivityExecutedAsync(workflowDefinitionID, workflowInstanceID, activityID, variableValues);
        }
    }
}
